### ISSUE TITLE
Add examples for `with_options()`

### ISSUE THREAD

**Issue by jimhester** [r-lib/withr#102]
Showing setting some option, then resetting it. Maybe one of the options that control printing would be a nice example?

Wild caught usage examples in the [GitHub search results for 'with_options'](https://github.com/search?q=with_options+user%3Acran&type=Code).

**Comment by moodymudskipper** [comment]
here are a couple:

```
with_options(list(scipen = "999"), print(exp(100)))
#> [1] 26881171418161356094440640202808862000420226

x <- 1
y <- "a"
with_options(list(show.error.messages = FALSE), {
  print(x)
  try(x <- x + 1)
  try(x <- x + y)
  print(x)
})
#> [1] 1
#> [1] 2
```

**Comment by jimhester** [comment]
@moodymudskipper if you would like to open a PR I would be grateful with this example I would be grateful!
