### ISSUE TITLE
withr::with_libpaths() and the peculiarities of utils::install.packages()

### ISSUE THREAD

**Issue by chasemc** [r-lib/withr#122]
This turns out to be (mostly) not a {withr} bug.  I'm posting what I've discovered through an unfortunate amount of troubleshooting in hopes it will help someone else.  

---
"Offending" Code:
```
a <- file.path(tempdir(), "temp")
dir.create(a)
withr::with_libpaths(a,
install.packages("purrr",
                 dependencies = "Imports")
                 )
list.dirs(a, recursive = FALSE)
```
#### Expected (Wanted) Outcome: 
{purrr} and its dependencies ({rlang}, {magrittr}) to be installed into `tempdir/temp`

#### Actual Outcome:
If {rlang}/{magrittr} are found in any directory within `.libPaths()`, they will not be installed in  `file.path(tempdir(), "temp")`; although {purrr} will be. 

The real problem is that I was getting seemingly different behavior on Windows vs Mac. On my Windows machines my external packages were installed to a different folder than either `.Library.site or .Library`. However, on my Mac they were installed to `.Library.site or .Library`.
This made it impossible to create a new package directory on my Mac that contained both a package **and** its dependencies (if the dependencies were already installed on that machine)

**Potential {withr} bug**: `withr::with_libpaths` doesn't create a pristine `.libPaths()`, even with `action = "replace`. This is because `.libPaths(new)` will still append `.Library.site, .Library` if they exist. AFAIK this is not changeable from within an R session and therefore I'm not sure there should be an `action = "replace"` option (or would require something like github.com/r-lib/callr)

---
#### It seems to start with `utils::install.packages()`:

It turns out that `install.packages` only respects `install.packages(lib=)` for the specified package (in this case {purrr}) and will ignore any dependencies ({magrittr}, {rlang}) if they are found in any of the directories in `.libPaths()`. This is IMO a really unfortunate quirk in R's {utils::install.packages()} for my case and those like here https://github.com/conda-forge/r-base-feedstock/issues/37, when people are trying to create isolated/standalone R compute environments.

#### The root of the "problem":
This behavior seems to be caused by the appending of .libPaths() *only during install of dependencies*:

https://github.com/wch/r-source/blob/d6c208e464d20adc6ce080ecfaaab4ccf3f06271/src/library/utils/R/packages2.R#L84-L88

**Comment by chasemc** [comment]
But now I'm thoroughly confused because this doesn't work on my Mac where rlang and magrittr are installed in the R installation library:

```
a <- file.path(tempdir(), "temp")
dir.create(a)

withr::with_envvar(
  c(R_LIBS = a,
    R_LIBS_USER = a,
    R_LIBS_SITE = a),{
  install.packages("purrr", dependencies = "Imports", lib = a)
  .libPaths()
})
  ```

**Comment by chasemc** [comment]
I'm wondering how packages like  `{renv}` handle this?

**Comment by jimhester** [comment]
Generally they handle it by only including a single library in `.libPaths()`. This also requires you _not_ to install 3rd party libraries into the system library. But as you say this is not really a withr bug, so I will close this issue.
