### ISSUE TITLE
`withr::defer_parent` doesn't work without `library(withr)` explicitly

### ISSUE THREAD

**Issue by randy3k** [r-lib/withr#123]
```r
foo <- function() {
    withr::defer_parent(cat("done"))
}

bar <- function() {
    foo()
}

bar()

```
results in
```
Error in defer(cat("done"), <environment>, c("first", "last")) :
  could not find function "defer"
```

However, appending `library(withr)` first will make the above work.

**Comment by randy3k** [comment]
Oh, it was fixed in #79

**Comment by jimhester** [comment]
@randy3k do you need this fix for anything urgently? We could probably do a CRAN release soonish, it has been some time since the last one.

**Comment by randy3k** [comment]
not really, especially there are workarounds. However, it is still good to have a new release for the bug fixes.
