### ISSUE TITLE
withr::with_preserve_seed() does not preserve is.null(.Random.seed)

### ISSUE THREAD

**Issue by HenrikBengtsson** [r-lib/withr#124]
Example:

```sh
$ Rscript --vanilla -e "str(.GlobalEnv$.Random.seed); withr::with_preserve_seed(x <- sample.int(1L)); str(.GlobalEnv$.Random.seed)"
 NULL
int [1:626] 10403 1 1586168631 257966637 -1833262268 2037450858 175878869 786533487 163480950 -2036568416 ...
```

```
> packageVersion("withr")
[1] '2.1.2'
```

**Comment by krlmlr** [comment]
I'm not sure it's even possible to preserve a NULL random seed. Can we solve this by documentation?

**Comment by HenrikBengtsson** [comment]
Sorry, I wasn't clear.  The value is not `NULL` - that's just a side effect of `<env>$` - its that it does not exist at all.  To solve it, first check `exists(".Random.seed", envir = .GlobalEnv)` (or `is.null(oseed)`).  Then, reset `.Random.seed` either to the old value or remove it using `rm(".Random.seed", envir = .GlobalEnv)`. This approach is used in several packages.

BTW, `.GlobalEnv$.Random.seed <- NULL` is not a valid seed.  It'll trigger warnings by R itself.

I'd say it's not sufficient to document.  A real-world problem where `withr::with_preserve_seed()` fail because of this is:
```r
$ R --quiet --vanilla
> exists(".Random.seed", envir = .GlobalEnv)
[1] FALSE
> library(ggplot2)
> exists(".Random.seed", envir = .GlobalEnv)
[1] TRUE
```
It's an unfortunate side effect that loading/attaching a package causes an update to the RNG state.  It prevents certain type of RNG validations. (This is actually how I tracked it down).

**Comment by jimhester** [comment]
#125 should fix this, after that change we have the following behavior (run in an interactive session so that the ggplot onload code would trigger)

```r
exists(".Random.seed", envir = .GlobalEnv)
#> [1] FALSE
library(ggplot2)
exists(".Random.seed", envir = .GlobalEnv)
#> [1] FALSE
```

**Comment by HenrikBengtsson** [comment]
Yes, LGTM. Thxs.  Not sure when you want to close this issue, so I leave that to you.
