### ISSUE TITLE
`defer()` on globalenv could mimic reg.finalizer?

### ISSUE THREAD

**Issue by daattali** [r-lib/withr#133]
I saw @jennybc 's [post](https://www.tidyverse.org/blog/2020/04/self-cleaning-test-fixtures/) about testing with `withr` and it talked about how `defer()` in the globalenv is strange. When I thought of defer in globalenv, I immediately though it would just act like `reg.finalizer()`. Is this not a good idea?

**Comment by jennybc** [comment]
@Hadley actually wondered out loud in the PR whether we should use `reg.finalizer()` to make sure the deferred global events actually run https://github.com/r-lib/withr/pull/76#pullrequestreview-394573897. If you scroll down, you can see the conversation. I actually don't feel like I *want* that behaviour.

I interpret the fact that this was merged without `reg.finalizer()` as weak affirmation that my view is OK. But maybe it's not completely settled?

**Comment by hadley** [comment]
I think both your argument and my argument have merits, but the advantage of guaranteeing clean up on exit are rather mild (since most of the time effects are session specific or in a session-specific temp directory anyway), that using `reg.finalizer()` would have few additional benefits.
