### ISSUE TITLE
Allow ... in local functions?

### ISSUE THREAD

**Issue by hadley** [r-lib/withr#142]
I think it's possible to do this with out breaking much existing code (assuming most people don't name the first argument)

```R
local_options <- function(.new = list(), ..., .local_envir = parent.frame()) {
  new <- utils::modifyList(.new, list(...))
  
  old <- set_options(new_options = new)
  defer(reset_options(old), envir = .local_envir)
  invisible(old)
}
```

**Comment by jimhester** [comment]
seems reasonable to me

**Comment by jakejh** [comment]
Related question, would you be open to the following change to `local_file` (with a similar change to `with_file`)? I'd like to use it to delete an entire folder.

```
local_file <- function(file, ..., .local_envir = parent.frame()) {
  file_nms <- names2(file)
  unnamed <- file_nms == ""
  file_nms[unnamed] <- as.character(file[unnamed])
  defer(unlink(file_nms, ...), envir = .local_envir)
  invisible(file)
}
```

**Comment by hadley** [comment]
@jakejh I think that would be best in a separate issue, because I think `local_directory()` would be a better name for that.

**Comment by jakejh** [comment]
Right, I was just trying to avoid confusion with `local_dir`, which should maybe instead be called `local_wd`.
