### ISSUE TITLE
Use .frame instead of .env/.local_env

### ISSUE THREAD

**Issue by hadley** [r-lib/withr#143]
It's more technically correct, and is less likely to be confusing if for functions (e.g. `local_bindings()`) that also need to specify an environment. (Would probably need to be implemented as part of #142, so could soft-deprecate old code.)

**Comment by jimhester** [comment]
I don't think the difference is really large enough to break backwards compatibility for.

**Comment by hadley** [comment]
I don't think you'd need to break backward compatibility. But I'm ambivalent about whether this is worth the effort or not. I think it's mostly the `.env` vs `.local_env` that bothers me.
