### ISSUE TITLE
Directories that delete themselves

### ISSUE THREAD

**Issue by jakejh** [r-lib/withr#144]
Currently `local_file` cannot delete directories, since by default `recursive = FALSE` for `unlink`. Here are some options.

1. Add ellipsis to `local_file` and `with_file`. This seems minimally redundant, but the function name could be confusing. In Unix, a directory is just a special type of file, right? ;-)
```r
local_file <- function(file, ..., .local_envir = parent.frame()) {
  file_nms <- names2(file)
  unnamed <- file_nms == ""
  file_nms[unnamed] <- as.character(file[unnamed])
  defer(unlink(file_nms, ...), envir = .local_envir)
  invisible(file)
}
```

2. @hadley suggested a `local_directory` function, which could be identical to the one above, or could be the following.
```r
local_link <- function(file, ..., .local_envir = parent.frame()) {
  file_nms <- names2(file)
  unnamed <- file_nms == ""
  file_nms[unnamed] <- as.character(file[unnamed])
  defer(unlink(file_nms, ...), envir = .local_envir)
  invisible(file)
}

local_file <- function(file, .local_envir = parent.frame()) {
  local_link(file, .local_envir = .local_envir)
}

local_directory <- function(directory, .local_envir = parent.frame()) {
  local_link(directory, recursive = TRUE, .local_envir = .local_envir)
}
```

If adding a function `local_directory`, it may be a good idea to deprecate the name `local_dir` in favor of `local_wd`. Thoughts?

**Comment by jimhester** [comment]
We can just add `recursive = TRUE` to the calls to unlink so this works.

**Comment by jakejh** [comment]
Sounds good to me, thanks!
