### ISSUE TITLE
Vignette illustrating `with_*()` and `local_*()` usage inside a function

### ISSUE THREAD

**Issue by jennybc** [r-lib/withr#145]
I just adapted content from the [Self-cleaning test fixtures](https://www.tidyverse.org/blog/2020/04/self-cleaning-test-fixtures/) blog post for inclusion in R Packages.

The main pivot was to talk about changing and restoring state in a *function* as opposed to in a *test*.

But it has started to feel like too much content to insert into the R code chapter.

Would you @jimhester entertain a PR for a withr vignette, which I could then refer to? I think this is a win-win: it lets me focus more on building awareness of the problem and would give withr more documentation re: how to use its functions in real life.

**Comment by jimhester** [comment]
sure
