### ISSUE TITLE
Issue installing withr in windows 10

### ISSUE THREAD

**Issue by mgorjis** [r-lib/withr#152]
I got this error when installing withr on R x64 4.0.2 in windows 10. Any idea how to fix this issue?

```
> install.packages("withr")
Installing package into ‘C:/Users/Mohammad/Documents/R/win-library/4.0’
(as ‘lib’ is unspecified)

  There is a binary version available but the source version is later:
      binary source needs_compilation
withr  2.2.0  2.3.0             FALSE

installing the source package ‘withr’

trying URL 'https://cloud.r-project.org/src/contrib/withr_2.3.0.tar.gz'
Content type 'application/x-gzip' length 91443 bytes (89 KB)
downloaded 89 KB

Error: '\U' used without hex digits in character string starting "'C:\U"
Execution halted

The downloaded source packages are in
        ‘C:\Users\Mohammad\AppData\Local\Temp\Rtmpc7T3wb\downloaded_packages’
Warning message:
In install.packages("withr") :
  installation of package ‘withr’ had non-zero exit status
```

**Comment by jimhester** [comment]
This is a setup issue with your R installation.

Somewhere, possibly a custom library path you have defined a variable like `C:\Users\\` when it should be `C:\\Users\\` or `C:/Users/`. In R all backslashes need to be doubled.

See https://stackoverflow.com/questions/29400338/error-when-installing-r-package

**Comment by mgorjis** [comment]
But even these commands don't fix the issue and I got the same error "Error: '\U' used without hex digits in character string starting "'C:\U"". And I do not have issue installing other R packages. The "withr" is the only package I got this error. 

```
 install.packages("withr", lib="C:\\Users\\Mohammad\\Documents\\R\\win-library\\4.0")
 install.packages("withr", lib="C:/Users/Mohammad/Documents/R/win-library/4.0")



```
