### ISSUE TITLE
Re-licensing withr

### ISSUE THREAD

**Issue by hadley** [r-lib/withr#154]
We are systematically re-licensing tidyverse and r-lib packages to use the MIT license, to make our package licenses as clear and permissive as possible. To do so, we need the approval of all copyright holders, which I have found by reviewing contributions from all all non-RStudio [contributors](https://github.com/r-lib/withr/graphs/contributors). @alexcipro, @angelinepro, @czeildi, @dragosmg, @dskard, @ellessenne, @lauracion, @malfaro2, @meta00, @mtmorgan, @richierocks, @siddharthab, @wendtke, @zkamvar, would you permit us to re-license withr with the MIT license? If so, please comment "I agree" below.

* [x] [@alexcipro](https://github.com/r-lib/withr/commits?author=alexcipro)  
* [x] [@angelinepro](https://github.com/r-lib/withr/commits?author=angelinepro)  
* [x] [@czeildi](https://github.com/r-lib/withr/commits?author=czeildi)  
* [x] [@dragosmg](https://github.com/r-lib/withr/commits?author=dragosmg)  
* [x] [@dskard](https://github.com/r-lib/withr/commits?author=dskard)  
* [x] [@ellessenne](https://github.com/r-lib/withr/commits?author=ellessenne)  
* [x] [@lauracion](https://github.com/r-lib/withr/commits?author=lauracion)  
* [x] [@malfaro2](https://github.com/r-lib/withr/commits?author=malfaro2)  
* [x] [@meta00](https://github.com/r-lib/withr/commits?author=meta00)  
* [x] [@mtmorgan](https://github.com/r-lib/withr/commits?author=mtmorgan)  
* [x] [@richierocks](https://github.com/r-lib/withr/commits?author=richierocks)  
* [x] [@siddharthab](https://github.com/r-lib/withr/commits?author=siddharthab)  
* [x] [@wendtke](https://github.com/r-lib/withr/commits?author=wendtke)  
* [x] [@zkamvar](https://github.com/r-lib/withr/commits?author=zkamvar)

**Comment by ellessenne** [comment]
Hi @hadley, I agree. Thanks!

**Comment by meta00** [comment]
I agree

**Comment by dragosmg** [comment]
I agree. Thanks!

**Comment by czeildi** [comment]
I agree

**Comment by malfaro2** [comment]
I agree

**Comment by dskard** [comment]
i agree

**Comment by zkamvar** [comment]
I agree

**Comment by mtmorgan** [comment]
I agree

**Comment by siddharthab** [comment]
I agree.

**Comment by angelinepro** [comment]
I agree.

**Comment by lauracion** [comment]
I agree

**Comment by richierocks** [comment]
I agree

**Comment by wendtke** [comment]
I agree. Thanks, @hadley.

**Comment by batpigandme** [comment]
Hi, @alexcipro, and @angelinepro,
We'd love to get your agreement please, if you could take a look when you have a chance. 🙂
Thanks!

**Comment by angelinepro** [comment]
I agree, I think I sent my agreement on October 30th.

**Comment by alexcipro** [comment]
I agree! Thank you!
