### ISSUE TITLE
Local dir who create the path

### ISSUE THREAD

**Issue by ArthurPERE** [r-lib/withr#164]
Hello,

It would be great that the local_dir and with_dir functions had an argument that if the directory we want to go is non-existent then the programme create this path recursively or not.

An argument like force or something like that, like in this function :

```
with_dir <- function(dir, expr, force = F, recurisive) {
  if (!dir.exists(dir) && force) {
    dir.create(dir, recursive = recursive)
  }
  withr::local_dir(dir)
  evalq(expr)
}
```

Thank you,
Arthur

**Comment by jimhester** [comment]
I would suggest you do something like this in these cases.

```r
withr::with_dir(fs::dir_create("foo/bar"), {
  my_code
})
```

We don't plan on adding this type of behavior to withr directly.
