### ISSUE TITLE
with_db_connection results in 'no visible binding for global variable' error

### ISSUE THREAD

**Issue by James-G-Hill** [r-lib/withr#168]
When using the `with_db_connection` function the names of the connections are set in the `con` variable as names in a named list.  Within the `code` section these names are then called as variables (as shown in the example in the reference: https://withr.r-lib.org/reference/with_db_connection.html).

However, because the name of the connection is defined within the list this results in the 'no visible binding for global variable' error when running Check.

Is there a way to resolve this error?

**Comment by jimhester** [comment]
Generally the best way to avoid this is adding the name to a whitelist with `utils::globalVariables()`

**Comment by James-G-Hill** [comment]
@jimhester That would be package-wide though so I'd have to ensure the same variable name isn't used in any other function in the package / shiny app?

**Comment by James-G-Hill** [comment]
I ended up using `local_db_connection` instead because that ensured I could create the connection variable within the function I wanted to run it, have no global variables, and still pass Check.  Any downsides to that I might consider?

**Comment by jimhester** [comment]
No, that is a fine solution.
