### ISSUE TITLE
Problem with `with_db_connection`

### ISSUE THREAD

**Issue by vanhry** [r-lib/withr#198]
I want to create safe db connection using `with_db_connection`, there is the logic of my code

```
library(withr)
library(RMySQL)

connect <- function() {
  con <- dbConnect(
    MySQL(),
    user = .username,
    password = .password,
    db = .schema,
    host = .hostname,
    client.flag = CLIENT_MULTI_STATEMENTS
  )
  return(con)
}

data <- with_db_connection(list(con=connect()),
                          code=dbGetQuery(con,  "SELECT * FROM some_data LIMIT 100"))
```

This code returns the `Error in .local(dbObj, ...) :  internal error in RS_DBI_getConnection: corrupt connection handle`

**Comment by hadley** [comment]
This simpler reprex appears to work for me:

``` r
library(withr)
with_db_connection(
  list(con = DBI::dbConnect(RSQLite::SQLite(), ":memory:")),
  DBI::dbGetQuery(con,  "SELECT 1 + 2 as three")
)
#>   three
#> 1     3
```

<sup>Created on 2024-01-10 with [reprex v2.0.2.9000](https://reprex.tidyverse.org)</sup>

You may have more luck using the more modern RMariaDB package.
