### ISSUE TITLE
Should the parameter `tmpdir` be superseded by a new `tempdir` parameter?

### ISSUE THREAD

**Issue by IndrajeetPatil** [r-lib/withr#203]
If you look at the signature for `{withr}` functions that work with temporary directories and files,

```r
with_tempdir(
  code,
  clean = TRUE,
  pattern = "file",
  tmpdir = tempdir(),
  fileext = ""
)
```

both the function suffix (`_tempdir`) and the default argument (`tempdir()`) follow the same naming pattern: `tempdir`.

But the function parameter is instead called `tmpdir` (notice the missing  _e_), and this naming inconsistency always trip me (and maybe others as well?) up while specifying a named argument.

Do you think it makes sense to [supersede](https://lifecycle.r-lib.org/articles/stages.html) this parameter with a new parameter called `tempdir`?

**Comment by MLopez-Ibanez** [comment]
> Do you think it makes sense to [supersede](https://lifecycle.r-lib.org/articles/stages.html) this parameter with a new parameter called `tempdir`?

This naming comes directly from the function `[tempfile()](https://stat.ethz.ch/R-manual/R-patched/library/base/html/tempfile.html)` in base R. And it is probably inspired by the environment variable `TMPDIR`, so changing this is probably a bad idea.

**Comment by IndrajeetPatil** [comment]
Good idea to not break the convention then.
