### ISSUE TITLE
local_assign()?

### ISSUE THREAD

**Issue by MichaelChirico** [r-lib/withr#205]
Another helper I find myself reaching for rather often is `local_assign()`.

This is useful for tests where we want a variable defined for a whole `test-*.R` file, but want to ensure the tests are more hermetic by hiding that variable from other files.

```r
# test-A.R
withr::local_assign(a = 1)

test_that("a", expect_identical(foo(), a))
test_that("b", expect_identical(bar(), sqrt(a)))

# test-B.R
test_that("a", expect_identical(baz(), a)) # should error!
```

`local_environment()` can be kludged to make this work, but it's not as natural for this use case.

**Comment by MichaelChirico** [comment]
For example, `local_environment()` is quite hard for defining sequentially-dependent variables:

```
withr::local_assign(a = 1)
withr::local_assign(b = a + 1)
```

accomplishing this with `local_environment()` would be hellish in general.

**Comment by lionel-** [comment]
This is implemented in `rlang::local_bindings()`. We don't plan to move it to withr since it uses rlang idioms like the `zap()` sentinel.
