### ISSUE TITLE
Provide more control over `defer_parent()` messages

### ISSUE THREAD

**Issue by jameslairdsmith** [r-lib/withr#206]
I have a use case where I'd like some code to run when a user's R session ends. Currently, when I use `defer_parent()` there is the following message that is shown.

https://github.com/r-lib/withr/blob/0d85fb5cfd89b2698b7c99c0c5d13e8cd47357e3/R/compat-defer.R#L67-L75

It would be useful to have some more control over this message, so that I could replace it with my own without having to fiddle with the text of the message in `withCallingHandlers()`. One option would be to have a `quiet=` argument. The other would be to use `rlang::inform()` (I see rlang is only suggested right now, so there's maybe a discussion to be had there).

**Comment by hadley** [comment]
Thanks for filing this issue! Unfortunately, I think it's out of scope for this package: we see this as mostly a convenience for developers, not a user facing feature. Even though I'm closing this issue, I really appreciate the feedback, and hope you'll continue to contribute in the future 😄
