### ISSUE TITLE
`with_options` differs from `options()`

### ISSUE THREAD

**Issue by fkohrt** [r-lib/withr#231]
I recently encountered two instances where I had to use `options()` rather than `withr::with_options()` to demonstrate something.

__First example__

In particular, the following R code leads to different results depending on whether `options()` or `withr::with_options()` is used:

```r
options(
  warnPartialMatchArgs = TRUE,
  warnPartialMatchDollar = TRUE,
  warnPartialMatchAttr = TRUE,
  warn = 2,
  lifecycle_verbosity = "error"
)
RSA::plotRSA(
    b0 = 0,
    x = 0.5,
    xy = 0.5,
    main = "Test",
    zlim = c(0, 1),
    xlim = c(0, 1),
    ylim = c(0, 1),
    legend = FALSE,
    param = FALSE
  )
```

...prints

![Rplot](https://github.com/r-lib/withr/assets/12914806/351c9da8-42a8-4a35-b293-86d9f467118b)

...while

```r
withr::with_options(list(
    warnPartialMatchArgs = TRUE,
    warnPartialMatchDollar = TRUE,
    warnPartialMatchAttr = TRUE,
    warn = 2,
    lifecycle_verbosity = "error"
), {
    RSA::plotRSA(
        b0 = 0,
        x = 0.5,
        xy = 0.5,
        main = "Test",
        zlim = c(0, 1),
        xlim = c(0, 1),
        ylim = c(0, 1),
        legend = FALSE,
        param = FALSE
    )
})
```

...outputs

```
Warning message:
The following aesthetics were dropped during statistical
transformation: fill
ℹ This can happen when ggplot fails to infer the correct grouping
  structure in the data.
ℹ Did you forget to specify a `group` aesthetic or to convert a
  numerical variable into a factor? 
```

__Second example__

Also,

```r
options(warnPartialMatchDollar = TRUE, warn = 2)
attitude |>
  ggplot2::ggplot(ggplot2::aes(x = rating, y = complaints)) +
  ggplot2::geom_point() +
  geomtextpath::geom_textsegment(
    x = 80,
    y = 80,
    xend = 50,
    yend = 50,
    label = "Test"
  )
```

...outputs

```
Error in label$xoff : 
  (converted from warning) partial match of 'xoff' to 'xoffset'
```

...while

```r
withr::with_options(list(
    warnPartialMatchDollar = TRUE, warn = 2
), {
    attitude |>
        ggplot2::ggplot(ggplot2::aes(x = rating, y = complaints)) +
        ggplot2::geom_point() +
        geomtextpath::geom_textsegment(
            x = 80,
            y = 80,
            xend = 50,
            yend = 50,
            label = "Test"
        )
})
```

...just works

![Rplot](https://github.com/r-lib/withr/assets/12914806/08d138e5-cb76-44c3-bbee-d639e4ebdbb5)

**Comment by lionel-** [comment]
Hello,

I don't know `plotRSA()` but there are two ways a function can produce the side effect of displaying a plot: when the function is called, or when the print method of a plot object it returns is called. In the latter case, if you don't call it explicitly within the `with_options()` context with an explicit `print()` call, then it's autoprint that will call it when the object is returned at top-level, outside of the `with_options()` context (and thus without the options set).

So I would try inserting a `print()` call in your code to see if that fixes it.

**Comment by fkohrt** [comment]
Ah yes, adding `print()` resolves the differences in both cases, thanks!

Closing this, as it's unrelated to {withr}.
