### ISSUE TITLE
More with_* function ideas

### ISSUE THREAD

**Issue by richierocks** [r-lib/withr#29]
### `with_device`

For saving base/lattice graphics.  Need to call `dev.off` on exiting.

I think that you get clearer code by having a different function for each device type, for example

``` r
with_png <- function(new, code)
{
  do.call(png, as.list(new))
  on.exit(dev.off())
  force(code)
}
```

with usage like

``` r
with_png("test.png", plot(1:10))
with_png(list("test2.png", width = 800, height = 600), plot(1:10))
```

You also need `with_tiff`, `with_pdf`, etc.
### `with_connection`

For file connections.  Need to call `close` on exiting.

This needs some thinking about.  I want to write

``` r
with_file <- function(new, code)
{
  conn <- do.call(file, as.list(new))
  on.exit(close(conn))
  # How to pass conn to the code?
  force(code)
}
with_file(list("test.txt", open = "w"), writeLines(LETTERS))
```

But you need to figure out the best way to pass the connection to `writeLines`/`readLines`/`cat`/whichever other function uses the connection.
### `with_db_connection`

Using `dbConnect` and `on.exit(dbdisconnect)`, but again you need a way to pass the connection to the code.

**Comment by krlmlr** [comment]
Does `with_png <- with_(png, dev.off)` work for you? 

The other two suggestions seem to require some global stack that stores the `old` values.

**Comment by richierocks** [comment]
This definition of `with_png` gives me an error: 

```{r}
with_png <- with_(png, dev.off)
with_png("test.png", plot(1:10))
## Error in match.arg(antialias, aa.win) : 'arg' must be of length 1
```

The problem occurs on the line `list(bitmap.aa.win = match.arg(antialias, aa.win))`, where `aa.win` is a constant in the `grDevices` package.  The problem is that if the first argument to `match.arg` isn't a formal argument of a function, then `match.arg` wants it to be a single string rather than a character vector.

--------

A similar function for PDFs gives a different error.

```{r}
with_pdf <- with_(pdf, dev.off)
with_pdf("test.pdf", plot(1:10))
## Error in if (which == 1) stop("cannot shut down device 1 (the null device)") : 
##   argument is of length zero
```

The plot does get written to file, but R is trying to shut down the wrong device.  If I call `dev.off()` after the error, then the plot file is correctly generated.

**Comment by jimhester** [comment]
There was some previous discussion about the device functions at https://github.com/jimhester/withr/pull/16#issuecomment-141090540

**Comment by krlmlr** [comment]
I forgot. Perhaps:

```
withr_ <- function(set, reset = set, transform = identity, envir = parent.frame()) { ... }
```

?

Then:

```
with_png <- with_(png, dev.off, function(x) dev.cur())
```

**Comment by jimhester** [comment]
Yeah I like that approach :+1:

**Comment by krlmlr** [comment]
@richierocks: Once #27 is merged, devices will be easy, e.g., for the pdf() device:

```
pdf_dev <- wrap(pdf, NULL, dev.cur())
with_pdf <- with_(pdf_dev, dev.off)
```

Would you like to contribute?

**Comment by richierocks** [comment]
@krlmlr @jimhester OK, I'm happy with the `with_device` functions now, so feel free to merge at your leisure.  

Still not quite sure how to go about the `with_connection`/`with_db_connection` functions.

**Comment by richierocks** [comment]
@krlmlr @jimhester 

### Feedback to your queries

> Could you please update your roxygen2 installation?

Done.

> The names "with_cairo_ps()" and "with_postscript()" look inconsistent to me.

Agreed, but there is a reason.  `cairo_ps` and `postscript` are the names of the devices in the `grDevices` package, so I'm consistently following that package's inconsistencies.

> Please double-check documentation of this argument.

I'd copied and pasted from the `with_locale` function. Now updated to use the template suggested by Jim.

> antialias <- match.arg(antialias) for jpeg_dev() and png_dev(), why is this necessary?

There are different implementations of `grDevices::png` and `grDevices::jpeg` depending upon your OS.  On Windows, the functions use a non-standard way of matching the possible values of `antialias`, and `jpeg_dev` and `png_dev` throw an error unless you call `match.arg` first.

> grDevices has man/unix and man/windows folders, it is possible for 
> external packages to do the same thing?

Not as far as I know, but I've asked the roxygen people.
See Issue https://github.com/klutometis/roxygen/issues/438

> we have been avoiding @importFrom declarations

Fixed.

### Another problem

The documentation for the `useDingbats` argument to `grDevices::pdf` differs between Unix and Windows: the Unix version has an extra sentence

> See the ‘Note’ for a possible fix for some viewers. 

When I build `withr` on Windows, instead of that sentence I get

> #ifdef unix not active 

and lots of warnings because R can't properly parse the rest of the Rd file.

The same issue occurs with the `command` argument to `grDevices::postscript`.

**Comment by jimhester** [comment]
I think we have included all of these ideas now, thanks again!
