### ISSUE TITLE
Think about value stack

### ISSUE THREAD

**Issue by krlmlr** [r-lib/withr#30]
For `with_tempfile()`, `with_connection()` and `with_db_connection()`. See also discussion in #29.

Need to find or create a package that implements a mutable stack.

Do we need to distinguish by type, for nested calls, so that we can ask "give me the innermost object of type x"?

**Comment by jimhester** [comment]
Hadley has a very straightforward stack implementation at

https://github.com/hadley/lineprof/blob/d034a7e0116886a997eae211efb932bf6ea73cee/R/shiny.r#L105-L127

**Comment by jimhester** [comment]
Also are you sure we need this? `on.exit()` calls seem to be lexically scoped to only the function they are defined in (not inner functions).
``` r
y <- function() {
  on.exit(str("one"))
}
x <- function() {
  on.exit(str("two"))
  y()
}
x()
#>  chr "one"
#>  chr "two"
```
Do you have an example which exhibits the deficiency, I am probably just missing it.

**Comment by krlmlr** [comment]
Example:

```
with_a(a,
  {
    with_b(b,
      {
        my_b <- get_current_b()
      }
    )
    my_a <- get_current_a()
  }
)
```

I guess that the implementation of get_current_x() requires some kind of stack, but I might be wrong.
