### ISSUE TITLE
with_library()

### ISSUE THREAD

**Issue by krlmlr** [r-lib/withr#38]
I'm looking for a clean way to run examples that call other packages without injecting `library()` calls. Would rather avoid using `::`.

Very rough sketch:

```
with_require <- with_(add_to_search, restore_search)

add_to_search <- function(pkg) {
  old_search <- search()
  pkg_id <- rev(paste0("package:", pkg))
  lapply(pkg_id, add_to_search_one)
  old_search
}

add_to_search_one <- function(pkg) {
  if (pkg %in% search()) {
    detach(pkg)
  }
  require(pkg, quietly = TRUE)
}

restore_search <- function(old_search) {
  ...
}
```

Possible extension: Generic environments, as in

```
with_require(list(env1 = new.env()), ...)
```

Thoughts?

**Comment by jimhester** [comment]
`require()` a mainly a thin wrapper around `library()`, why not just use `library(pkg, quietly = TRUE)` and call this `with_library`.

As you probably know R doesn't support 100% clean unloading of a package.

In particular `devtools::unload()` has some extra logic to force a namespace to be unloaded (`devtools::unregister_namespace()` and unload compiled dlls (`devtools::unload_dll()`). We would probably want to do something similar here.

R currently does not remove functions from the S3 methods registry when they are unloaded, which can lead to lazy load errors. See https://stat.ethz.ch/pipermail/r-devel/2015-December/072150.html for details. We may want to explicitly remove them, or just force all the promises as I did in devtools.

**Comment by krlmlr** [comment]
What a mess. I wouldn't mind if with_require() loaded but didn't unload namespaces.

Agree to call it with_library() and drop quietly = TRUE (so that the user is warned when a package is loaded).
