### ISSUE TITLE
with_envvar_unset

### ISSUE THREAD

**Issue by krlmlr** [r-lib/withr#41]
```
  with_envvar_unset <- withr::with_(
    function(x) {
      old <- Sys.getenv(x, names = TRUE)
      Sys.unsetenv(x)
      old
    },
    Sys.setenv
  )
```

Integrating this into `with_envvar()` is another option: Unset all elements that are NULL. Interface becomes incompatible with Sys.setenv() but this is not necessarily a bad thing.

**Comment by jimhester** [comment]
`with_envvar` already allows unsetting environment variables by using `NA`.

> if ‘NA’ is used those environment variables will be unset.
