### ISSUE TITLE
local_tempfile

### ISSUE THREAD

**Issue by hadley** [r-lib/withr#55]
It occurs to me that the first argument could default to `tempfile()` and the path could be returned

This might be a useful pattern elsewhere - `with_*()` can't easily pass a value into the block (unless we use NSE or require anonymous functions), but `local_` doesn't have the same problem.

**Comment by jimhester** [comment]
I like the idea of an anonymous function for `with_tempfile()` would be a better API and we could make tempfiles for each of the arguments to the function...

Also returning the paths from `local_` makes lots of sense.

This idiom would also be useful for things like `with_connection()` and `with_db()` and scoped equivalents.

**Comment by krlmlr** [comment]
I found the following pattern for passing values into the block:

``` r
with_con <- function(con, code) {
  force(con)
  code
}

with_con(con1 <- "test", {
  con1
})
#> [1] "test"
```

Would this be an alternative?

**Comment by jimhester** [comment]
No, that also sets `con1` in the parent frame.

```r
x
print(identity(x <- 1))
x
```

The current behavior using a named list as the first argument seems good to me. It keeps the implementation relatively simple with only minimal additional syntax.

The `local_` variants have been switched to returning the value as suggested, so I am closing this.
