### ISSUE TITLE
with_options() restores only the options listed in `new`

### ISSUE THREAD

**Issue by wlandau-lilly** [r-lib/withr#57]
```r
library(withr)
getOption("undefined")
## NULL
with_options(new = list(some_other_option = 5), {
  options(undefined = "user_defined")
})
getOption("undefined")
## "user_defined"
```

Do we want to restore all the options, not just those in `new`?

**Comment by jimhester** [comment]
No, I think the current behavior is easier to reason about personally.

**Comment by wlandau-lilly** [comment]
That makes sense. What about a totally separate function that restores the full set of global options? If that does not sound good to you, I will close this issue.

**Comment by jimhester** [comment]
I don't really see the use case, if you want to restore an option define it in the arguments, otherwise explicitly call `options()` and restore it with `on.exit()`.

**Comment by jimhester** [comment]
If you really want to do this it is easy to write the function yourself.

```r
with_all_options <- function(code) {
  old <- options()
  on.exit(options(old))
  code
}
```

**Comment by wlandau-lilly** [comment]
`with_all_options()` is exactly what I am talking about. I worry about having to hunt for all the options I may or may not have messed with, and some packages may have strange hidden side effects. Whether or not it becomes part of `withr`, I will use it.

**Comment by wlandau-lilly** [comment]
I am finding that I need to work a little harder to restore options that were previously `NULL`, so maybe there is a need to have it pre-packaged somewhere.

```r
with_all_options <- function(code) {
  old <- options()
  on.exit(restore_options(old))
  force(code)
}

restore_options <- function(old){
  current <- options()
  remove_these <- setdiff(names(current), names(old))
  removal_list <- as.list(old[remove_these])
  names(removal_list) <- remove_these
  do.call(options, removal_list)
  options(old)
}
```

I know it is weird to reset options back to `NULL`, but it turns out to be the safe thing to do for my use case.

I rely on global options to architect the unit testing of [drake](https://github.com/wlandau-lilly/drake) (wlandau-lilly/drake#58). The same core `testthat` workflow needs to work under all evaluation environments, parallel backends, and reasonable levels of scale. So I define multiple testing scenarios and use a [global option](https://github.com/wlandau-lilly/drake/blob/master/R/test_scenarios.R) to identify the current one. I only use the default scenario for CRAN and CI services, but I occasionally need to [loop through](https://github.com/wlandau-lilly/drake/blob/master/R/test_scenarios.R#L22) [all the scenarios](https://github.com/wlandau-lilly/drake/blob/master/R/testing_scenarios.R) to be sure the high-overhead, platform-dependent stuff works too. The added automation was a huge relief.
