### ISSUE TITLE
Allowing multiple message sinks to the same file

### ISSUE THREAD

**Issue by wlandau-lilly** [r-lib/withr#58]
`with_message_sink()` deliberately avoids creating two message `sink()`s on the same file. I am wondering if you might consider relaxing this behavior somehow, maybe with something like `with_message_sink(..., allow_multiple = TRUE)`. See [this SO post](https://stackoverflow.com/questions/46962608/multisession-parallelism-with-a-shared-stderr-redirect) for a use case that would greatly benefit.

**Comment by jimhester** [comment]
Even if this was supported, having multiple processes with connections to the same file isn't going to work without file locking. I think you need to go about this in a different way.

**Comment by wlandau-lilly** [comment]
Fair enough. For what it's worth, I ended up going with [a solution that writes to a different file for each PID](https://github.com/wlandau-lilly/drake/blob/master/R/hooks.R#L32).
