### ISSUE TITLE
New feature: with_cluster()

### ISSUE THREAD

**Issue by wlandau-lilly** [r-lib/withr#59]
I am picturing a function that reaps zombie children on error, something like the following.

```r
with_cluster <- function(cl, code){
  withCallingHandlers(
    code,
    error = function(e){
      parallel::stopCluster(cl)
      stop(e)
    }
  )
}
```

**Comment by jimhester** [comment]
While useful, I think cluster management is a big enough issue it should probably be implemented elsewhere.

**Comment by IndrajeetPatil** [comment]
I wanted to create the exact same FR issue! 

I think the proposed context manager has general enough utility to merit its inclusion in `{withr}` itself, rather than a more specialized package.
