### ISSUE TITLE
lattice may be unused

### ISSUE THREAD

**Issue by QuLogic** [r-lib/withr#62]
`lattice` was moved from `Suggests` to `Imports` in 26a2ddfebc39bb48637264c13da3ee7551cd4cc3, but it seems like it may not be used. The [CRAN check log](https://www.r-project.org/nosvn/R.check/r-devel-linux-x86_64-fedora-gcc/withr-00check.html) says it's not imported from.

A search shows it only used in `tests/testthat/test-devices.R`, so maybe it was an accident.

**Comment by jimhester** [comment]
Yes you are correct, it should be moved to Suggests, thanks!
