### ISSUE TITLE
Suggestion: with_temp_dir

### ISSUE THREAD

**Issue by DarwinAwardWinner** [r-lib/withr#63]
For code that needs to create a large number of temporary files, it may be more convenient to create a single temporary directory, create any files it needs to in that directory, and then recursively delete that directory when it finishes. I suggest a function `with_temp_dir` that encapsulates this pattern. It would work like Python 3's `tempfile.TemporaryDirectory` context manager.

**Comment by wlandau** [comment]
Maybe something like this?

```r
with_new_tempdir <- function(code){
  tmp <- tempfile()
  dir.create(tmp)
  withr::with_dir(new = tmp, code = code)
}
```

**Comment by DarwinAwardWinner** [comment]
That's more or less what I'm proposing, but with the option (enabled by default) to delete the directory and all its contents afterward.

**Comment by wlandau** [comment]
Are you worried about storage? In my experience, `/tmp` empties on its own fairly regularly.

**Comment by DarwinAwardWinner** [comment]
It's still better to clean up automatically when possible instead of relying on the system to clean up eventually, especially when working with large data sets (e.g. bioinformatics, with multi-GB files containing millions of DNA sequences).
