### ISSUE TITLE
use withr::with_options to pass shiny.maxRequestSize to a shiny app

### ISSUE THREAD

**Issue by VincentGuyader** [r-lib/withr#72]
Hi, I have an issue using `with_option` to launch a shiny app with the correct option

I dont understand why this code doesn't work as expected :

```
library(shiny)

ui <- fluidPage(
  verbatimTextOutput("option"),
  verbatimTextOutput("option2"),
  actionButton("go","go")
)

server <- function(input, output, session) {
  output$option <- renderText({getOption("repos")})
  output$option2 <- renderText({ getOption("shiny.maxRequestSize") })
}

withr::with_options(list(shiny.maxRequestSize="find_me"), {
  shiny::shinyApp(ui, server)
})
```

this app should show "find_me" inside a textouput do I make a typo? getOption("shiny.maxRequestSize") have to be 'find_me', why not?

I certainly can add this option inside the server, but I prefere to use with_option.

**Comment by jimhester** [comment]
Does setting the option by hand work, I am guessing no? e.g.

```r
options(shiny.maxRequestSize="find_me")
shiny::shinyApp(ui, server)
```

**Comment by VincentGuyader** [comment]
yes, it works :

```
library(shiny)

ui <- fluidPage(
  verbatimTextOutput("option"),
  verbatimTextOutput("option2"),
  actionButton("go","go")
)

server <- function(input, output, session) {
  output$option <- renderText({getOption("repos")})
  output$option2 <- renderText({ getOption("shiny.maxRequestSize") })
}
options(shiny.maxRequestSize="find_me")
shiny::shinyApp(ui, server)
```
![image](https://user-images.githubusercontent.com/10470699/40441120-5e05b894-5ec0-11e8-8c8e-5cf0d00ff1fe.png)

**Comment by jimhester** [comment]
There isn't really anything we can do in this package, when you call `shiny::shinyApp()` R runs the `on.exit()` handlers for the current block (which is what unsets the option). Here is an example without withr.

```r
# ... code as above
local({
  options(shiny.maxRequestSize = "find_me")
  on.exit({str("hi"); options(shiny.maxRequestSize = NULL)})
  shiny::shinyApp(ui, server)
  })
#> chr "hi"
```
