### ISSUE TITLE
callr issue

### ISSUE THREAD

**Issue by dslramsey** [r-lib/withr#83]
This was picked up while tracking down an issue on the rstan forum on a Win10 x64 system.  R 3.5.1.

`system2("R", args = "CMD config CC")`
works but
`callr::rcmd_safe("config", "CC")`
errors with
`Error in eval(substitute(expr), data, enclos = parent.frame()) :
is.character(repos) is not TRUE`
when called from `pkgbuild::has_build_tools` and @bgoodri in case it has anything to do with how rstan is calling it

**Comment by jimhester** [comment]
Ok, but why have you opened the issue in the withr directory?

**Comment by bgoodri** [comment]
I'm sorry. I asked @dslramsey to open an issue an accidentally pointed him to the callr repo rather than withr .

**Comment by dslramsey** [comment]
Apologies for the mistake.  I'll post this on the correct repo..
