### ISSUE TITLE
Let with_tempfile() and local_tempfile() be directories

### ISSUE THREAD

**Issue by gaborcsardi** [r-lib/withr#84]
Since R does not actually create the file (it really should, it is insecure not to, but that's another story), the temp file can actually be a directory. But then we need to clean it up with `unlink(..., recursive = TRUE)`.

**Comment by jimhester** [comment]
Or should we just have `with_tempdir()` to create a temp directory? I guess this would be slightly confusing with the default R temp directory.

**Comment by gaborcsardi** [comment]
Yeah, I thought about that, and I agree it would be confusing. I think adding the `recursive = TRUE` will probably  not hurt anyone, and it does cover this use case.

**Comment by gaborcsardi** [comment]
Want me to do a PR?

**Comment by jimhester** [comment]
Sure

**Comment by jimhester** [comment]
The main thing to do for this is add `recursive = TRUE` to the unlink call at https://github.com/r-lib/withr/blob/79c5e3630b2c30bbff1f90c5220e47cb514592de/R/tempfile.R#L17 and for `local_tempfile()`.
