### ISSUE TITLE
Release withr 2.1.3

### ISSUE THREAD

**Issue by javierluraschi** [r-lib/withr#85]
Any chance we can update `withr` in CRAN?

I'm trying to figure out if we can rely on having https://github.com/r-lib/withr/pull/81 on CRAN or if a workaround should be put in place for the R `arrow` bindings.

**Comment by jimhester** [comment]
We can, but probably not before RStudio::conf unless you really need it.

**Comment by jimhester** [comment]
We release withr 2.2.0 last week, so this can be closed now.
