### ISSUE TITLE
with_bindings()

### ISSUE THREAD

**Issue by hadley** [r-lib/withr#87]
This would be very similar to `with()`, and fills in an important side-effect that withr doesn't currently control.

**Comment by jimhester** [comment]
e.g. something like this

```r
x <- 10
with_bindings(c(x = 20), x)
#> [1] 20
```

**Comment by jimhester** [comment]
Sketch of implementation

``` r
with_bindings <- function(bindings, code, envir = parent.frame()) {
  env <- list2env(as.list(bindings), parent = envir)
  eval(substitute(code), env)
}

x <- 10
with_bindings(c(x = 20), x)
#> [1] 20
x
#> [1] 10
```

<sup>Created on 2019-06-21 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by hadley** [comment]
That won't work if the code modifies the environment. I think the best you can do is get and reset?

**Comment by jimhester** [comment]
Why wouldn't it work? You are expecting the code to be run in the calling environment?

**Comment by hadley** [comment]
Yeah, like all the other withr functions?

**Comment by lionel-** [comment]
Probably best to not duplicate functionality with `rlang::with_bindings()`? Without depending on rlang, withr won't be able to support things like `rlang::zap()`, and we'll have disparate functionality.

**Comment by jimhester** [comment]
Honestly I would be fine not implementing this.

**Comment by hadley** [comment]
I guess I don't mind if it only lives in rlang. The interface is currently slightly inconsistent, but it would be mostly made consistent by #142, and #143, if we can persuade @jimhester it's worth it 😄

**Comment by lionel-** [comment]
Sounds good, let's settle on using `rlang::with_bindings()`.
