### ISSUE TITLE
use of the help argument in `with_package`

### ISSUE THREAD

**Issue by moodymudskipper** [r-lib/withr#94]
The `help` argument of `with_package` is not documented explicitly : 

> help	
> the name of a package, given as a name or literal character string, or a character string, depending on whether character.only is FALSE (default) or TRUE).

To understand what it does I looked into the code and saw it was just forwarded to `library`, there I read the same argument description in `?library` but the details say : 

> library(help = somename) computes basic information about the package somename, and returns this in an object of class "packageInfo".

Does it make sense having this argument in `with_package` ?

Moreover `help` has no default value while other arguments that didn't have a default value in `library` have one in `with_package`. Wouldn't it be more consistent (and [tidy](https://principles.tidyverse.org/args-hidden.html)) to have a default value for `help` as well (if it makes sense to keep the argument).

**Comment by jimhester** [comment]
The code currently forwards all arguments from `library()`, but you are correct forwarding help doesn't make a lot of sense, and confuses the issue. I think we can simply remove the argument from `with_package()`.
