### ISSUE TITLE
Add examples for `with_libpaths()`

### ISSUE THREAD

**Issue by jimhester** [r-lib/withr#99]
Maybe showing setting an alternative libpaths and installing a package, would have to be careful though, it might have to be in `\dontrun{}`

Wild caught usage examples in the [GitHub search results for 'with_libpaths'](https://github.com/search?q=with_libpaths+user%3Acran&type=Code).

**Comment by moodymudskipper** [comment]
I think no need to install with `with_libpaths()` as we can just use `installed.packages()`, but more relevant to `with_temp_libpaths()`, I chose to install *fortunes* as it is fun harmless dependency free, and I can use `unloadNamespace()` on it without breaking anything.

```
# will be TRUE on a default installation
with_libpaths(.libPaths()[[1]], "withr" %in% installed.packages()[,"Package"])
# will be FALSE on a default installation
with_libpaths(.libPaths()[[2]], "withr" %in% installed.packages()[,"Package"])

# install package fortunes in temp folder, 
with_temp_libpaths({
  print(.libPaths())
  unloadNamespace("fortunes") # unload in case it was already attached/loaded
  install.packages("fortunes", quiet = TRUE)
  pkgs <- installed.packages()[,"Package"]
  print("fortunes" %in% pkgs)
  print("withr" %in% pkgs)
  library(fortunes)
},"replace")

# can now be used as it is loaded , even if it is not installed in current .libPath
fortune()
```

**Comment by jimhester** [comment]
Added with 4650387
